Adiciona post retrospectiva + visus analógicas
OpenDevUFCG/OpenDevUFCGBlog pull request #31
Opened 2019-12-31 00:26 UTC by ivynasantino

2019-12-31 01:10 UTC, JRobsonJr requested changes
Ivyna, amei muito a postagem, vai ser algo bem diferente para a gente. As visualizações ficaram maravilhosas!! Deixei algumas sugestões de revisão no documento. Qualquer dúvida pelo motivo de ter uma ou outra sugestão é só falar!

2019-12-31 01:10 UTC, JRobsonJr commented on texts/v0.0.1/POST_RETROSPECTIVA_VISU_ANALOGICAS.md
> +O ano 2019, a organização fez 1 ano, e como resultado, tivemos crescimento da organização, com a criação de novos projetos, como podemos observar na imagem a seguir.
Fiz umas sugestões pra diminuir umas repetições na frase, mas fique à vontade para mudar caso eu tenha mudado a ideia/você prefira de outra forma \o/
```suggestion
Em 2019, a OpenDevUFCG completou um ano e, como resultado, tivemos o crescimento da equipe e do número de projetos, como podemos observar na imagem a seguir.
```

2019-12-31 01:10 UTC, JRobsonJr commented on texts/v0.0.1/POST_RETROSPECTIVA_VISU_ANALOGICAS.md
> +Tendo em vista que o core cresceu, também tivemos mais ideias de projetos surgindo, é o que você vai ver na próxima imagem:
```suggestion
Tendo em vista que o time _Core_ cresceu, também tivemos mais ideias de projetos surgindo. É o que você vai ver na próxima imagem:
```

2019-12-31 01:10 UTC, JRobsonJr commented on texts/v0.0.1/POST_RETROSPECTIVA_VISU_ANALOGICAS.md
> +É de grande satisfação ver o crescimento de nossos projetos e que nosso espírito de comunidade está impactando muitas pessoas, e como resultado, ver que nossa ideia está influenciando as pessoas a sa
```suggestion
É de grande satisfação ver o crescimento de nossos projetos e que nosso espírito de comunidade está impactando muitas pessoas, e como resultado, ver que nossa ideia está influenciando as pessoas a querer saber mais e participar de projetos _open source_. 
```

2019-12-31 01:10 UTC, JRobsonJr commented on texts/v0.0.1/POST_RETROSPECTIVA_VISU_ANALOGICAS.md
> +Então movidos por isso, pensamos em organizar o Hacktoberfest, um evento para reunir boas ideias e pessoas legais para ajudar à comunidade, através de palestras, minicursos, hacktime e chuva de ideia
```suggestion
Então, movidos por isso, pensamos em organizar o **Hacktoberfest OpenDevUFCG**, um evento para reunir boas ideias e pessoas legais para ajudar a comunidade através de atividades como palestras, minicursos, HackTime e abertura para sugestões. Agradecemos muito pelo apoio de todos, doadores e patrocinadores que compraram a ideia e deram apoio para o evento acontecer! Mas, deixando um pouco as palavras de lado, que tal ver os dados disso tudo?
```

2019-12-31 01:10 UTC, JRobsonJr commented on texts/v0.0.1/POST_RETROSPECTIVA_VISU_ANALOGICAS.md
> +[O projeto](http://www.dear-data.com/theproject)
```suggestion
- [O projeto](http://www.dear-data.com/theproject);
```

2019-12-31 01:10 UTC, JRobsonJr commented on texts/v0.0.1/POST_RETROSPECTIVA_VISU_ANALOGICAS.md
> +[Vídeo TED](https://www.ted.com/talks/giorgia_lupi_how_we_can_find_ourselves_in_data)
```suggestion
- [Vídeo TED](https://www.ted.com/talks/giorgia_lupi_how_we_can_find_ourselves_in_data);
```

2019-12-31 01:10 UTC, JRobsonJr commented on texts/v0.0.1/POST_RETROSPECTIVA_VISU_ANALOGICAS.md
> +[Livro](http://www.dear-data.com/thebook)
```suggestion
- [Livro](http://www.dear-data.com/thebook);
```

2019-12-31 01:10 UTC, JRobsonJr commented on texts/v0.0.1/POST_RETROSPECTIVA_VISU_ANALOGICAS.md
> +[Medium @Giorgia Lupi](https://medium.com/@giorgialupi)
```suggestion
- [Medium @Giorgia Lupi](https://medium.com/@giorgialupi).
```

2019-12-31 01:10 UTC, JRobsonJr commented on texts/v0.0.1/POST_RETROSPECTIVA_VISU_ANALOGICAS.md
> +Então gente, é isto, de novo gostaria de agradecer a cada um que acredita em nossos projetos e na nossa comunidade, foi um ano muito legal para nossa organização, de bastante crescimento e de aprendi
```suggestion
Então, gente, é isto, de novo gostaria de agradecer a cada um que acredita em nossos projetos e na nossa comunidade! Foi um ano muito legal para nossa organização, de bastante crescimento e de aprendizado, e sempre saibam, estamos dispostos para ajudar. Obrigada pela leitura, até ano que vem!
```

2019-12-31 01:10 UTC, JRobsonJr commented
Ah, mais uma ideia: que tal botar uma foto dos organizadores no Hacktoberfest como capa da postagem? Acho que ficaria bem bonitinho <3

2020-02-14 18:00 UTC, JuanBarros2 approved these changes

2020-10-03 18:28 UTC, juliobguedes approved these changes

2020-10-03 18:28 UTC, merged